import { Product, ProductStatus, CheckoutLog } from '@/types/inventory';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'MacBook Pro 16"',
    description: 'High-performance laptop for development work',
    category: 'Laptop',
    location: 'Storage Room A',
    status: ProductStatus.AVAILABLE,
    serialNumber: 'MBP16-2024-001',
    purchaseDate: new Date('2024-01-15'),
    value: 2499,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Dell Monitor 27"',
    description: '4K monitor for design work',
    category: 'Monitor',
    location: 'Conference Room B',
    status: ProductStatus.IN_EVENT,
    pickedBy: 'John Doe',
    serialNumber: 'DM27-2024-005',
    purchaseDate: new Date('2024-02-01'),
    value: 399,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    name: 'Canon EOS R5',
    description: 'Professional camera for photography',
    category: 'Camera',
    location: 'Equipment Storage',
    status: ProductStatus.DEFECTIVE,
    serialNumber: 'CR5-2024-003',
    purchaseDate: new Date('2024-01-20'),
    value: 3899,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '4',
    name: 'iPad Pro 12.9"',
    description: 'Tablet for presentations and design',
    category: 'Tablet',
    location: 'Marketing Department',
    status: ProductStatus.IN_REPAIR,
    serialNumber: 'IP12-2024-007',
    purchaseDate: new Date('2024-01-25'),
    value: 1099,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '5',
    name: 'Projector Epson',
    description: 'Portable projector for presentations',
    category: 'Projector',
    location: 'Conference Room A',
    status: ProductStatus.AVAILABLE,
    serialNumber: 'EP-2024-012',
    purchaseDate: new Date('2024-02-05'),
    value: 899,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '6',
    name: 'Wireless Microphone',
    description: 'Professional wireless microphone system',
    category: 'Audio',
    location: 'Audio Equipment Storage',
    status: ProductStatus.IN_EVENT,
    pickedBy: 'Sarah Johnson',
    serialNumber: 'WM-2024-018',
    purchaseDate: new Date('2024-02-10'),
    value: 299,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-18'),
  },
];

export const mockCheckoutLogs: CheckoutLog[] = [
  {
    id: '1',
    productId: '2',
    action: 'CHECKOUT',
    previousStatus: ProductStatus.AVAILABLE,
    newStatus: ProductStatus.IN_EVENT,
    pickedBy: 'John Doe',
    location: 'Conference Room B',
    notes: 'Needed for quarterly presentation',
    timestamp: new Date('2024-02-20T10:30:00'),
    updatedBy: 'admin',
  },
  {
    id: '2',
    productId: '2',
    action: 'STATUS_CHANGE',
    previousStatus: ProductStatus.IN_EVENT,
    newStatus: ProductStatus.AVAILABLE,
    location: 'Storage Room A',
    notes: 'Returned after presentation',
    timestamp: new Date('2024-02-19T14:15:00'),
    updatedBy: 'admin',
  },
  {
    id: '3',
    productId: '3',
    action: 'STATUS_CHANGE',
    previousStatus: ProductStatus.AVAILABLE,
    newStatus: ProductStatus.DEFECTIVE,
    notes: 'Lens mechanism jammed',
    timestamp: new Date('2024-02-10T09:00:00'),
    updatedBy: 'admin',
  },
  {
    id: '4',
    productId: '6',
    action: 'CHECKOUT',
    previousStatus: ProductStatus.AVAILABLE,
    newStatus: ProductStatus.IN_EVENT,
    pickedBy: 'Sarah Johnson',
    location: 'Conference Room C',
    notes: 'Event recording session',
    timestamp: new Date('2024-02-18T11:45:00'),
    updatedBy: 'admin',
  },
];